repos:
  - repo: local
    hooks:
      - id: poetry-lock
        name: Check poetry.lock consistency
        language: system
        entry: poetry check --lock
        always_run: true
        pass_filenames: false
      - id: lint
        name: Run poe lint
        language: system
        entry: poetry run poe lint
        always_run: true
        pass_filenames: false
